eureka:
  instance:
    preferIpAddress: true # register the IP of the service rather than the server name
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    baseUrl: http://localhost:9411
  cloud:
    stream:
      bindings:
        # maps the input channel to the orgChangeTopic queue
        input:
          destination: orgChangeTopic
          contentType: application/json
          # group property guarantees process-once semantics for a service i.e. message consumed by one instance of a service should not be consumed by other instances
          group: licensingGroup
        binder:
          zkNodes: localhost
          brokers: localhost

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/user