server:
  port: 8888

eureka:
  instance:
    preferIpAddress: true # register the IP of the service rather than the server name
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/