server:
  port: 8901

eureka:
  instance:
    # register the IP of the service rather than the server name (prefer ip address, default is DNS. DNS does not work with containers but IP address does)
    preferIpAddress: true
  client:
    registerWithEureka: true
    # pull down a local copy of the registry
    fetchRegistry: true
    # location of Eureka service
    serviceUrl:
      defaultZone: http://localhost:8761/eureka