eureka:
  instance:
    preferIpAddress: true # register the IP of the service rather than the server name
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    # spring cloud stream message broker
    stream:
      bindings:
        # maps to Source.output() channel
        output:
          # name of the message queue (or topic)
          destination: orgChangeTopic
          contenxtType: application/json
        # use Kafka as a message bus in the service (could also be RabbitMQ as an alternative)
        kafka:
          binder:
            # tells Spring Cloud Stream the network location of your Kafka and ZooKeeper
            zkNodes: http://localhost
            brokers: http://localhost
      kafka:
        binder:
          brokers: localhost

  zipkin:
    baseUrl: http://localhost:9411

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/user