package de.etecture.microservices.organizationservice;

import brave.sampler.Sampler;
import de.etecture.microservices.organizationservice.utils.UserContextFilter;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.circuitbreaker.EnableCircuitBreaker;
import org.springframework.cloud.stream.annotation.EnableBinding;
import org.springframework.cloud.stream.messaging.Source;
import org.springframework.context.annotation.Bean;
import org.springframework.security.oauth2.config.annotation.web.configuration.EnableResourceServer;

import javax.servlet.Filter;

@SpringBootApplication
@EnableCircuitBreaker
@EnableResourceServer // indicates that it is a protected resource, can be accessed via token generated by OAuth2
@EnableBinding(Source.class) // bind application to a message broker
public class OrganizationServiceApplication {

    @Bean
    public Filter userContextFilter() {
        return new UserContextFilter();
    }

    @Bean
    public Sampler defaultSampler() {
        return Sampler.ALWAYS_SAMPLE;
    }

    public static void main(String[] args) {
        SpringApplication.run(OrganizationServiceApplication.class, args);
    }

}
